version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_HOSTNAME
        - DB_USER
        - DB_PASSWORD
        - DB_DATABASE
    container_name: lwt
    depends_on:
      - lwt_db
    ports:
      - "8010:80"
    restart: unless-stopped
  lwt_db:
    container_name: lwt_db
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
    hostname: ${DB_HOSTNAME}
    image: mariadb:10.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
        - lwt_db_data:/var/lib/mysql
volumes:
  lwt_db_data:
